[package]
name = "hello-world-lunatic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
submillisecond = {path = "../../../../submillisecond", default-features = false}
http = "0.2.7"